### ISSUE TITLE
http2: panic serving

### ISSUE THREAD

**Issue by ser** [neodyme-labs/influx_log#2]
i have config file identical to the caddyfile in readme, but caddy debug shows:

```
{"level":"debug","ts":1669038308.5923817,"logger":"http.stdlib","msg":"http2: panic serving 188.199.199.222:8214: runtime error: index out of range [4] with length 1\ngoroutine 1736286 [running]:\nn
et/http.(*http2serverConn).runHandler.func1()\n\tnet/http/h2_bundle.go:5899 +0x125\npanic({0x203fa60, 0xc000055170})\n\truntime/panic.go:838 +0x207\ngithub.com/neodyme-labs/influx_log.(*InfluxWriter).Write(0xc054baee40, {0xc003183b00?, 0x21baa70?, 0xc?})\n\tgithub.com/neodyme-labs/influx_log@v0.0.3/main.go:177 +0x6d8\ngo.uber.org/zap/zapcore.(*ioCore).Write(0xc054fb6ba0, {0x0, {0xc0d6fe19234c6668, 0xf003326d31d, 0x3689120}, {0xc000055050, 0x14}, {0x21cc82c, 0xf}, {0x0, ...}, ...}, ...)\n\tgo.uber.org/zap@v1.23.0/zapcore/core.go:99 +0xb5\ngo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc002336750, {0xc0120eec80, 0x5, 0x5})\n\tgo.uber.org/zap@v1.23.0/zapcore/entry.go:255 +0x1d9\ngo.uber.org/zap.(*Logger).Info(0x40b04b?, {0x21cc82c?, 0x40d9c7?}, {0xc0120eec80, 0x5, 0x5})\n\tgo.uber.org/zap@v1.23.0/logger.go:213 +0x59\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP.func1()\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/server.go:262 +0x8ca\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc00022b180, {0x25cc1f0, 0xc0000caa88}, 0xc05c86cb00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/server.go:290 +0x15d3\nnet/http.serverHandler.ServeHTTP({0x6a55e0?}, {0x25cc1f0, 0xc0000caa88}, 0xc05c86c700)\n\tnet/http/server.go:2916 +0x43b\nnet/http.initALPNRequest.ServeHTTP({{0x25cde10?, 0xc000
36a540?}, 0xc003263c00?, {0xc00c6e8000?}}, {0x25cc1f0, 0xc0000caa88}, 0xc05c86c700)\n\tnet/http/server.go:3523 +0x245\nnet/http.(*http2serverConn).runHandler(0x25c5fb0?, 0x36bb380?, 0x0?, 0x0?)\n\tnet/http/h2_bundle.go:5906 +0x78\ncreated by net/http.(*http2serverConn).processHeaders\n\tnet/http/h2_bundle.go:5636 +0x59b"}
```

server: influxdb2 2.5.1-1 - but as far as i can see, caddy does not even try to contact it

any suggestions?

**Comment by kilimnik** [comment]
That seems odd. I did update the package to a new version. Because it was a bit hacky.

Make sure to add the json encoder.

**Comment by ser** [comment]
Fresh build works like a charm, many thanks! 🥰
